name: Hourly Evanston Weather Update

on:
  schedule:
    - cron: '0 */4 * * *'  # Run every hour
  workflow_dispatch:      # Allow manual triggers

jobs:
  update-weather:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.4.28"

    - name: Setup Python
      uses: actions/setup-python@v5

    - name: Run weather script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # For the LLM service
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      run: uv run foggybot.py

    - name: Commit and push if changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add weather_report.json captures/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update weather report [skip ci]" && git push)
